### ISSUE TITLE
Unrecognized options

### ISSUE THREAD

**Issue by oisvidi** [nelmio/NelmioSecurityBundle#100]
I get this error trying to run cache:clear
> php bin/console cache:clear
> 
>   [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                                          
>   Unrecognized options "level1_fallback, browser_adaptive, block-all-mixed-content" under "nelmio_security.csp.enforce"  

Symfony version: 3.0.6
NelmioSecurityBundle version: 1.10.0

Config file:

```
nelmio_security:
    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY
    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # Forces Microsoft's XSS-Protection with
    # its block mode
    xss_protection:
        enabled: true
        mode_block: true
    csp:
        #report_logger_service: logger
        hosts: []
        content_types: []
        enforce:
            # see full description below
            level1_fallback: true
            # Only send directives supported by the browser, defaults to false
            # This is a port of https://github.com/twitter/secureheaders/blob/83a564a235c8be1a8a3901373dbc769da32f6ed7/lib/secure_headers/headers/policy_management.rb#L97
            browser_adaptive: false
            report-uri: ['/nelmio/csp/report']
            default-src: [ 'self' ]
            #frame-src: [ 'https://www.youtube.com' ]
            script-src:
                - 'self'
                - maps.googlemaps.com
            img-src:
                - 'self'
                - maps.googlemaps.com
            block-all-mixed-content: false # Default to false, blocks http content over https transport
```

Is it a config problem?
