### ISSUE TITLE
Report URI not working in other environments than PROD

### ISSUE THREAD

**Issue by bgatellier** [nelmio/NelmioSecurityBundle#108]
Hello,

I'm facing an issue when I try to use the report feature of the bundle in the DEV environment: the blocked content generate an uri without the `app_dev.php` prefix.

I'm using Symfony 3.1.0 with the 2.0.0 version of the bundle.

routing.yml:
```
# NelmioSecurityBundle
nelmio_security:
    path:     /csp/report
    defaults: { _controller: nelmio_security.csp_reporter_controller:indexAction }
    methods:  [POST]
```

config.yml:
```
nelmio_security:
    csp:
        enforce:
            # see full description below
            level1_fallback: true
            # Only send directives supported by the browser, defaults to false
            # This is a port of https://github.com/twitter/secureheaders/blob/83a564a235c8be1a8a3901373dbc769da32f6ed7/lib/secure_headers/headers/policy_management.rb#L97
            browser_adaptive: false
            report-uri: /csp/report
            connect-src:
                - 'self'
                - 'api.mapbox.com'
                - '*.tiles.mapbox.com'
            default-src:
                - 'self'
            font-src:
                - 'self'
                - 'fonts.gstatic.com'
            img-src:
                - 'self'
                - 'data:' # Allows data: URIs to be used as a content source (@see https://developer.mozilla.org/fr/docs/Web/Security/CSP/CSP_policy_directives#Data) 
                - '*.tiles.mapbox.com'
            script-src:
                - 'self'
                - 'www.google-analytics.com'
                - 'api.tiles.mapbox.com'
            style-src:
                - 'self'
                - 'unsafe-inline' # Because of the FancyBox Javascript library
                - 'fonts.googleapis.com'
                - 'api.tiles.mapbox.com'
            block-all-mixed-content: true # Default to false, blocks http content over https transport
            # upgrade-insecure-requests: true # Default to false, upgrades http requests to https transport
        report:
            # see full description below
            level1_fallback: true
            # Only send directives supported by the browser, defaults to false
            # This is a port of https://github.com/twitter/secureheaders/blob/83a564a235c8be1a8a3901373dbc769da32f6ed7/lib/secure_headers/headers/policy_management.rb#L97
            browser_adaptive: false
            report-uri: /csp/report
            script-src:
                - 'self'
```

**Comment by bgatellier** [comment]
I just tried with fresh install of Symfony 3.0.6 and 2.8.6, but the behavior is still here, with both PHP5 & 7 :/

**Comment by jayS-de** [comment]
Additional to your normal bundle configuration, just try it in your config_dev.yml with this:

```
nelmio_security:
    csp:
        enforce:
            report-uri: /app_dev.php/nelmio/csp/report
```

But i would advice you instead of using the http://localhost/app.php/ or http://localhost/app_dev.php/ access, to configure different vhosts or just run application twice on different ports on time with env dev and one time with env prod like this:

```
php bin/console server:start -p8000 --env dev
php bin/console server:start -p8001 --env prod
```

So that both applications are now running independently and can be called by http://localhost:8001/ for prod and http://localhost:8000/ for dev

**Comment by bgatellier** [comment]
I'll give a try with the embedded web server, thx.

Btw, is there any reason why this bundle does not work with the app_dev.php ?

**Comment by jayS-de** [comment]
The reason is, that the report uri is an absolute location and a route.

When you start your server and the default is the app.php which means production environment all requests are pointing to the production system. This was the reason why it may help to just point the reporting URL to another location if your app runs in dev mode.

But any way it's way more secure to just use separated runtimes.

**Comment by romainneutron** [comment]
You can use

```yml
nelmio_security:
    csp:
        enforce:
            report-uri: %router.request_context.base_url%/csp/report
```

It should solve your issue
