### ISSUE TITLE
Exclude NelmioSecurityBundle from API routes

### ISSUE THREAD

**Issue by thomas2411** [nelmio/NelmioSecurityBundle#118]
Is there a possibility now or could it be added to exclude adding NelmioSecurityBundle info on response to API calls? For instance don't add no-sniff and other stuff to responses generate for ^/api?

**Comment by sstok** [comment]
Something like that does exist for `clickjacking` but not for the no-sniff or csp 🤔
But adding paths may not be what you want, instead I would favor a RequestMatcher service-id.

**Comment by thomas2411** [comment]
I think this is beyond my knowledge. You suggest to add RequestMatcher service which will remove these items from the response headers if this is an API call?

**Comment by sstok** [comment]
No suggest to add an option to the Bundle's to `clickjacking` configuration to _allow_ configuring a custom RequestMatcher which determines if this header should be added or not.

**Comment by romainneutron** [comment]
Hello @thomas2411 

You can disable these features based on the content-type of the response. For instance:

```
nelmio_security:
    clickjacking:
        content_types: ['text/html']
    csp:
        content_types: ['text/html']
```
