### ISSUE TITLE
Version 2.2.0 without ua-parser/uap-php

### ISSUE THREAD

**Issue by sgehrig** [nelmio/NelmioSecurityBundle#132]
`composer.json` defines `ua-parser/uap-php` as a dev-dependency. Since version 2.2.0 (commit #815b5d762ae26db93195abc3c7cc1a9f09f75ee7) *NelmioSecurityBundle* doesn't work out of the box any more with the default configuration.

This happens because the new configuration setting 

```YAML
nelmio_security:
    csp:
        report_endpoint:
            filters:
                browser_bugs: true # default
```

requires the `ua-parser/uap-php` library to be installed. That's somehow inconsistent as the other setting that relies on the `ua-parser/uap-php` library 

```YAML
nelmio_security:
    csp:
        report/enforce:
            browser_adaptive:
                enabled: false # default
```

is disabled by default. The solution could be to

1. disable the `browser_bugs` filter by default
2. make the default setting for `browser_bugs` dependant on the availability of `ua-parser/uap-php`
3.  require the `ua-parser/uap-php` library in `composer.json`

Does this make any sense?
