### ISSUE TITLE
Error after upgrading to 2.5

### ISSUE THREAD

**Issue by willemstuursma** [nelmio/NelmioSecurityBundle#174]
Got this error after running `composer update`:

    In ContainerBuilder.php line 1022:
    You have requested a non-existent service "nelmio_security.csp_report.filter".

This service isn't referenced anywhere in my project.

Going back to 2.4.0 works fine. 

Using Symfony 3.4.

**Comment by rpkamp** [comment]
Works fine for me on Symfony 3.4.

Have you tried clearing your cache? If that doesn't help could you post your entire configuration maybe?

**Comment by willemstuursma** [comment]
After cleaning the cache, I still have the problem.

This is in my `config.yml`:
```yml
nelmio_security:
    content_type:
        nosniff: true
    csp:
        enabled: false
    xss_protection:
        enabled: true
        mode_block: true
```
