### ISSUE TITLE
CSP content_types stopped working

### ISSUE THREAD

**Issue by thomas2411** [nelmio/NelmioSecurityBundle#199]
I have just realized that on Symfony 4.2 project the setting of content_types stopped working:

Previously I have used:
```
    csp:
        enabled: true
        report_logger_service: logger
        hosts: []
        content_types: ['text/html']
```

Now it doesn't work. It doesn't show CSP headers at all.
Even when I have changed it to:
```

    csp:
        enabled: true
        report_logger_service: logger
        hosts: []
        content_types: ['text/html; charset=utf-8','text/html; charset=UTF-8', 'text/html']
```
