### ISSUE TITLE
Content security policy blocks everything on iOS Safari v5.1.1

### ISSUE THREAD

**Issue by TheHackerDev** [nelmio/NelmioSecurityBundle#25]
I have my content security policy set as follows:

```
nelmio_security:
   # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY
    # prevents redirections outside the website's domain
    external_redirects:
        log: true
        override: homepage

    # prevents inline scripts, unsafe eval, external scripts/images/styles/frames, etc
    csp:
        report_uri: /nelmio/csp/report
        report_only: false
        default: [ self ]
        frame: [ 'https://www.youtube.com' ]
        script:
            - self
            - 'https://www.google-analytics.com'
            - 'http://www.google-analytics.com'
        img:
            - self
            - 'https://www.google-analytics.com'
            - 'http://www.google-analytics.com'

    # disables content type sniffing for script resources
    content_type:
        nosniff: true
```

So, the csp setting should not be blocking scripts, css, and javascript from loading on the page. However, on my first-generation iPad, running iOS 5.1.1 (last supported version on that iPad) is not loading any of these assets due to my content security policy; this is using both Chrome and Safari.

My last resort would be disabling the content security policy for any iOS devices; is there a way to do this? However, I would like to be able to make this work across all versions of devices.
