### ISSUE TITLE
Can't use environment variables to enable/disable features

### ISSUE THREAD

**Issue by janklan** [nelmio/NelmioSecurityBundle#311]
The subject says it all. When I try to use an environment variable to turn something on/off, I get a following error:

```Environment variables "bool:FORCE_SSL" are never used. Please, check your container's configuration.```

Versions:
* nelmio/security-bundle: v3.0.0 
* PHP: 8.1.5
* Symfony: 6.0.8

Working configuration:

```yaml
nelmio_security:
    forced_ssl:
        enabled: true
```

Broken configuration:

```yaml
parameters:
    env(FORCE_SSL): 'true'
    
nelmio_security:
    forced_ssl:
        enabled: '%env(bool:FORCE_SSL)%'
```

I ran following experiments:

1. Stop declaring a default value in `parameters` section: didn't help
2. Stop casting the value into boolean: the error changed to `Invalid type for path "nelmio_security.forced_ssl.enabled". Expected "bool", but got "string".` or whatever type did I use. Using `(int) 0` is not coerced to `false`
3. Try to use the environment variable in `nelmio_security.referrer_policy.enabled`: same result
