### ISSUE TITLE
Unexpecting appearance of unsafe-inline on CSP

### ISSUE THREAD

**Issue by spyridonas** [nelmio/NelmioSecurityBundle#346]
Hello,
I believe i have found a bug, or that my knowledge of CSP is lacking.
Given the following csp configuration:
```
    csp:
        enforce:
            level1_fallback: false
            browser_adaptive:
                enabled: false
            connect-src:
                - 'self'
```
The content security policy correctly show the connect-src policy only.

If i add the same thing on default-src, making the configuration look like this:
```
    csp:
        enforce:
            level1_fallback: false
            browser_adaptive:
                enabled: false
            connect-src:
                - 'self'
            default-src:
                - 'self'
```

Then the response includes unsafe-inline as well.
Is this a known issue ? Or is it expected behaviour ?
