### ISSUE TITLE
Is it posible to override csp for specified route? 

### ISSUE THREAD

**Issue by hd-deman** [nelmio/NelmioSecurityBundle#36]

**Comment by jrobeson** [comment]
i have a use case for this feature!  The WebProfilerBundle can be used on live sites, especially since one can use request matchers to provide profiles for specific requests/paths/etc.  

However, it is impossible for the WebProfilerBundle to work with CSP setups that are close to being strict due to all the inline styles, assets, and scripts.

**Comment by jrobeson** [comment]
I was just about to add a whiteList paramter to the ContentSecurityPolicyListener.  I've already added the appropriate tests as well.  Should something different be done instead?

**Comment by Seldaek** [comment]
I think supporting path-based config would be most flexible because you can then have different strictness levels on different sections of the app, but a whitelist would be an easier solution to implement for sure.. Up to you but if you have time for a fully fledged version (i.e. what clickjacking does) that'd be great.

**Comment by jrobeson** [comment]
can you do a bit of a snippet of how you think it might look under the  bundle configuration (as yaml).  tryin to think about how it might work with the various configurations of report, enforce and how default-src is the default for everything.

**Comment by jrobeson** [comment]
Why did you move to enforce and report being top level nodes instead of options of default-src,frame-src, etc anyways?

**Comment by Seldaek** [comment]
The idea is just to have two configs, one for the main CSP header and one for the report-only header.

From this:

```
nelmio_security:
    csp:
        report_logger_service: logger
        enforce:
            report-uri: /nelmio/csp/report
            default-src: [ 'self' ]
            frame-src: [ 'https://www.youtube.com' ]
            script-src:
                - 'self'
                - 'unsafe-inline'
            img-src:
                - 'self'
                - facebook.com
                - flickr.com
        report:
            report-uri: /nelmio/csp/report
            script-src:
                - 'self'
```

We could go to:

```
nelmio_security:
    csp:
        report_logger_service: logger
        paths:
            - ^/foo:
                enforce:
                    report-uri: /nelmio/csp/report
                    default-src: [ 'self' ]
                    frame-src: [ 'https://www.youtube.com' ]
                    script-src:
                        - 'self'
                        - 'unsafe-inline'
                    img-src:
                        - 'self'
                        - facebook.com
                        - flickr.com
                report:
                    report-uri: /nelmio/csp/report
                    script-src:
                        - 'self'
            - ^/:
                report:
                    report-uri: /nelmio/csp/report
                    script-src:
                        - 'self'
```

So you could define rules per path, and you could either define report/enforce OR paths at the top level.

If you see a better way I am fully open to suggestions :)

**Comment by jrobeson** [comment]
I'm just trying to make sure it's not awkard to be able to apply the same config to multiple paths as such that i can say both ^/_wdt and ^/_profiler get the same configuration without duplicating it for each.

I'd prefer not to try to encompass it all in a single regex, but i guess we could:

```yaml
paths: '^/_(wdt|profiler)'
  enforce:
    # ...
```

vs: 

```yaml
paths:
  - '[^/_wdt', ^/_profiler']
    enforce:
      # ...
```
which feels a little weird to me, but maybe it's not not as bad as i think it is.

**Comment by jrobeson** [comment]
If we can come up with an agreement about this, then we'd end up with 3 configs to parse, the new one, the current one, and the legacy one.

What should be done about that? should we bump the major version and drop both other configs, or just drop the (current) "legacy" config.

**Comment by thkoch2001** [comment]
Just leave ```report``` and ```enforce``` as they are now and add ```path``` at the same level. If a route matches a defined path than it takes the config from there. Otherwise the default config from the 'global' report and enforce settings is applied.

```yaml
nelmio_security:
    csp:
        report_logger_service: logger
        report:
            report-uri: /nelmio/csp/report
            script-src:
                - 'self'
        enforce:
            report-uri: /nelmio/csp/report
            img-src:
                - 'self'
                - facebook.com
        paths:
            - ^/foo:
                enforce:
                    report-uri: /nelmio/csp/report
                    default-src: [ 'self' ]
                    frame-src: [ 'https://www.youtube.com' ]
                report:
                    report-uri: /nelmio/csp/report
                    script-src:
                        - 'self'
```
