### ISSUE TITLE
FlexibleSSL on remember me cookie not redirecting to https

### ISSUE THREAD

**Issue by aistis-** [nelmio/NelmioSecurityBundle#55]
A site uses flexible SSL for logged users. Index page you can access with both `http` and `https`.
On logging to the site with remember me flag to cookies are set:

* `REMEMBER_ME` with 1 year expire
* `auth` with 1 year expire

The `auth` cookie's expiration length is set on `EventListener/FlexibleSslListener.php` by finding the longest all cookies expiration from the `Response`.

The problem ocurs when after closing the browser (deleting session cookie) trying access http index. On redirect (because found `auth` cookie with value `'1'`) the cookie `auth` is reseted again with expiration 0 (till session end), because it cannot be calculate from an empty cookies array in the `Response`.

```
# app/config/config.yml
nelmio_security:
    flexible_ssl:
        cookie_name: auth
        unsecured_logout: false

security:
    firewalls:
       main:
            remember_me:
                secure: true
                key: secret_key
                name: REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
```

```
// EventListener/FlexibleSslListener.php

    public function onPostLoginKernelResponse(FilterResponseEvent $e)
    {
        if (HttpKernelInterface::MASTER_REQUEST !== $e->getRequestType()) {
            return;
        }

        $response = $e->getResponse();

        $longestExpire = 0;
        foreach ($response->headers->getCookies() as $cookie) {
            // find longest expiration time
            $longestExpire = max($longestExpire, $cookie->getExpiresTime());
            if (!$cookie->isSecure()) {
                // force existing cookies (remember-me most likely) to be secure
                $response->headers->setCookie(new Cookie(
                    $cookie->getName(),
                    $cookie->getValue(),
                    $cookie->getExpiresTime(),
                    $cookie->getPath(),
                    $cookie->getDomain(),
                    true,
                    $cookie->isHttpOnly()
                ));
            }
        }

        // set the auth cookie
        $response->headers->setCookie(new Cookie(
            $this->cookieName,
            '1',
            $longestExpire,
            '/',
            null,
            false,
            false
        ));

        // force session cookie to be secure
        $params = session_get_cookie_params();
        $response->headers->setCookie(new Cookie(
            session_name(),
            session_id(),
            0,
            $params['path'],
            $params['domain'],
            true,
            $params['httponly']
        ));
    }
```

A possible solution could be to set `auth` cookie when no `auth` cookie exists on the `Request`.

```
if (null === $e->getRequest()->cookies->get($this->cookieName)) {
    // set the auth cookie
    $response->headers->setCookie(new Cookie(
        $this->cookieName,
        '1',
        $longestExpire,
        '/',
        null,
        false,
        false
    ));
}
```

What do you think guys?
