### ISSUE TITLE
Change behavior of Clickjacking Listener

### ISSUE THREAD

**Issue by montaniasystemab** [nelmio/NelmioSecurityBundle#67]
I would like to discuss changing the behavior of Clickjacking Listener to let multiple rules set the header instead of stopping after the first match. 

The current implementation returns after the first match: https://github.com/nelmio/NelmioSecurityBundle/blob/master/EventListener/ClickjackingListener.php#L51

This makes this kind of configuration impossible: 

``` yml
# bundle.yml - default deny everything
nelmio_security:
    clickjacking:
        paths:
            '^/.*': DENY
```

``` yml
# config.yml - override one path for this app
imports:
    - { resource: "@Bundle/Resources/config/bundle.yml" }

nelmio_security:
    clickjacking:
        paths:
            '^/files/': SAMEORIGIN
```

Would this change even make sense? It would possible be a BC change so might have to wait for next major version.
